config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:create]
  end
  resources :posts, except: [:create] do
    resources :comments, only: [:new, :create]
  end


  root to: redirect("/subs")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :subs, :author, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub, inverse_of: :posts
  has_many :comments, dependent: :destroy, inverse_of: :post
  # belongs_to :sub, inverse_of: :posts

  belongs_to :author,
    class_name: :User,
    primary_key: :id,
    foreign_key: :user_id,
    inverse_of: :posts
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text             not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator, presence: true

  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post, inverse_of: :subs
  # has_many :posts, inverse_of: :sub

  belongs_to :moderator,
    class_name: :User,
    primary_key: :id,
    foreign_key: :user_id,
    inverse_of: :subs
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_login
  
  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    render :show
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.user_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_user.subs.find_by(id: params[:id])
    render :edit
  end

  def update
    @sub = current_user.subs.find_by(id: params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = ["Can't edit this sub"]
      render :edit
    end
  end

  def destroy
    @sub = current_user.subs.find_by(id: params[:id])
    @sub.destroy!
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

app/views/subs/edit.html.erb
<h2>Edit Your Sub</h2>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br>
  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  <br><br>

  <label>Description
  <textarea name="sub[description]" >
    <%= @sub.description %>
  </textarea>
  </label>
  <br><br>

  <input type="submit" value="Submit">

</form>

app/views/subs/index.html.erb
<h1>WhaSSubs</h1>
<ul>
  <% @subs.each do |s| %>
    <li><%= link_to s.title, sub_url(s) %> </li>
  <% end %>
</ul>

<%= link_to "Create New Sub", new_sub_url %>

app/views/subs/new.html.erb
<h2>Create New Sub</h2>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <br>
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>
  <br><br>

  <label>Description
  <textarea name="sub[description]" >

  </textarea>
  </label>
  <br><br>

  <input type="submit" value="Submit">

</form>

app/views/subs/show.html.erb
<h3>Title: <%= @sub.title %></h3>

<p><b>Description:</b> <%= @sub.description %></p>

<br>
<ul>
  <% @sub.posts.each do |post| %>
    <li>
      <b><%= link_to post.title, post_url(post) %></b>
      <span><%= post.content %></span>
    </li>
  <% end %>
</ul>
<br>

<b>Add post</b>
  <form action="<%= sub_posts_url(@sub) %>" method="post">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <br>
    <label>Title
      <input type="text" name="post[title]" value="">
    </label>
    <br><br>
    <label>Url (optional)
      <input type="text" name="post[url]" value="">
    </label>
    <br><br>

    <% Sub.all.each do |s| %>
      <label>
        <input type="checkbox" name="post[sub_ids][]" value="<%= s.id %>">
        <%= s.title %>
      </label>
      <br>
    <% end %>

    <input type="hidden" name="post[sub_id]" value="@sub.id">

    <label>Content
    <textarea name="post[content]" >

    </textarea>
    </label>
    <br><br>

    <input type="submit" value="Submit">

  </form>


<br>
<%= button_to "Edit your sub", edit_sub_url(@sub), method: :get %>
<%= button_to "Delete your sub", sub_url(@sub), method: :delete %>

app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>