config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]
  resources :subs do
    resources :posts, only: [:create]
  end
  resources :posts, except: [:create] do
    resources :comments, only: [:new, :create]
  end


  root to: redirect("/subs")
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :subs, :author, presence: true

  has_many :post_subs, dependent: :destroy, inverse_of: :post
  has_many :subs, through: :post_subs, source: :sub, inverse_of: :posts
  has_many :comments, dependent: :destroy, inverse_of: :post
  # belongs_to :sub, inverse_of: :posts

  belongs_to :author,
    class_name: :User,
    primary_key: :id,
    foreign_key: :user_id,
    inverse_of: :posts
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    # @post.sub_id = params[:sub_id]

    if @post.save

      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to root_url
    # redirect_to sub_url(@post.subs)
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<h3>Edit your post</h3>
  <form action="<%= post_url(@post) %>" method="post">
    <input type="hidden" name="_method" value="patch">

    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <br>
    <label>Title
      <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    <br><br>
    <label>Url (optional)
      <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>
    <br><br>

    <b>Associated Subs</b>
    <br>
    <% Sub.all.each do |s| %>
      <label>
        <input
          type="checkbox"
          name="post[sub_ids][]"
          value="<%= s.id %>"
          <%= "checked" if @post.sub_ids.include?(s.id) %> >
        <%= s.title %>
      </label>
      <br>
    <% end %>
    <br>

    <label>Content
    <textarea name="post[content]" >
      <%= @post.content %>
    </textarea>
    </label>
    <br><br>

    <input type="submit" value="Submit">

  </form>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/show.html.erb
<h3>Title: <%= @post.title %></h3>
<ul>
  <li>Url: <a href="#"><%= @post.url %></a></li>
  <li>Content: <%= @post.content %></li>
  <li>posted by <%= @post.author.username %></li>

  <br>
  <b>Associated Sub</b>
  <ul>
    <% @post.subs.each do |s| %>
      <li><%= link_to s.title, sub_url(s) %></li>
    <% end %>
  </ul>
  <br>

  <b>Comment:</b>
  <% @post.comments.each do |comment| %>
    <li><%= comment.content %></li>
  <% end %>

</ul>
<br>

<%= button_to "Add a Comment", new_post_comment_url(@post), method: :get %>
<%= button_to "Edit your post", edit_post_url(@post), method: :get %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>